version: '3.7'
 
services:
  mainline:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: "1.17.9-perl"
        BUILD_FILE: "debian.conf"
    image: app:mainline
    container_name: nginx_mainline
 
  stable:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: ${DEFAULT_NGINX_VERSION}
        BUILD_FILE: "debian.conf"
    image: app:${DEFAULT_NGINX_VERSION}
    container_name: nginx_stable
 
  alpine:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: "1.17.9-alpine-perl"
        BUILD_FILE: "alpine.conf"
    image: app:alpine
    container_name: nginx_alpine